version: "3.7"
services:
  ui:
    image: sillydong/influxdb-ui
    ports:
      - "8080:80"
  influxdb:
    image: influxdb
    volumes:
      - "./influxdb-data:/var/lib/influxdb"
    environment:
      INFLUXDB_USER: "${INFLUXDB_DB}"
      INFLUXDB_DB: "${INFLUXDB_USER}"
      INFLUXDB_USER_PASSWORD: "${INFLUXDB_USER_PASSWORD}"
    ports:
      - "8086:8086"
  grafana:
    image: grafana/grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "${GF_SECURITY_ADMIN_PASSWORD}"
      GF_SERVER_ROOT_URL: "${GF_SERVER_ROOT_URL}"
      GF_AUTH_ANONYMOUS_ENABLED: "true"
    ports:
      - "3000:3000"
    volumes:
      - "./grafana-data:/var/lib/geafana"
